### ISSUE TITLE
Use web instead of docroot?

### ISSUE THREAD

**Issue by q0rban** [Lullabot/trusty32-lamp#31]
Should we consider switching from assuming `docroot` to assuming `web` for the web root? This is what [drupal-project](https://github.com/drupal-composer/drupal-project) uses.

**Comment by deviantintegral** [comment]
I originally used docroot because that's what Acquia used, and you couldn't change it. Do you know if that's still the case? If not, perhaps we make this a configuration option? It wouldn't be too difficult to ship two different apache site configs with different docroots, and swap them out with a provisioning shell script in the Vagrantfile.

**Comment by q0rban** [comment]
Interesting background on the discussion: https://github.com/drupal-composer/drupal-project/issues/64

**Comment by q0rban** [comment]
I think a symlink is fine in most circumstances, so perhaps this is just a documentation thing. When does a symlink not work? I did run into some funkiness with using a symlink and it not reading the .htaccess  file, but I think when I looked closer it was a PEBKAC error.

**Comment by deviantintegral** [comment]
I just tested using a symlink and everything seems OK. I'm going to file a docs update for that.
